### ISSUE TITLE
Support for ASH 3.0

### ISSUE THREAD

**Issue by ravides19** [bcksl/ash_geo#3]
Hi @bcksl can you pls add support for Ash 3.0 I think the dependencies are breaking and not allowing me to use with Ash3.0

**Comment by camstuart** [comment]
+1 I am interested in Ash, but my app relies on geo queries so I was really excited to see this package existed! 

I don't think there are breaking changes that would cause a problem, so it may only be a case of relaxing the deps requirements

**Comment by zachdaniel** [comment]
This package has already been updated to support 3.0. Perhaps it's missing a release on hex? In the meantime, try pointing at the github dependency :)

**Comment by camstuart** [comment]
Great idea!

```elixir
{:ash_geo,
       git: "https://github.com/bcksl/ash_geo.git",
       ref: "496a57465c6ee25160af38ff5f06deff647da55f"},
```
Works.

Thanks for updating this @zachdaniel

**Comment by zachdaniel** [comment]
@bcksl could we get a 3.x compatible release on hex?

**Comment by bcksl** [comment]
Just got back from abroad, apologies for the delay on this. New version is up as `0.3.0` on Hex.
